### ISSUE TITLE
License not specified

### ISSUE THREAD

**Issue by felix-b** [jamarino/IntervalTree#1]
Hey @jamarino, first, kudos for creating this library!

It seems that the project contains no license.
There is a MIT license link in the NuGet page that navigates to https://licenses.nuget.org/MIT, which is generic license text with placeholders. 

AFAIK, no one can legally use your library until there is an explicit license that allows otherwise.
Could you please add a LICENSE file to the project?

**Comment by jamarino** [comment]
Hi @felix-b!

Thank you for raising this, I did not realise that was an issue. I'll be sure to look into that and fix it ASAP!

**Comment by jamarino** [comment]
@felix-b Once again, thank you for your feedback.

I've raised a [pull request with my planned changes](https://github.com/jamarino/IntervalTree/pull/2/files) regarding the license. I welcome any feedback/concerns.

Once merged, I'll be sure to update the repository license information as well and publish an updated NuGet package.

Cheers!

**Comment by felix-b** [comment]
@jamarino Thank you so much for responding so quickly.
MIT is perfect 💯

**Comment by jamarino** [comment]
@felix-b Update complete. Version 1.2.0 is live on nuget.org.

Enjoy! 🎉
